resources:
    AppBundle\Entity\Player:
        itemOperations:
            get:
                method: 'GET'
                route_name: 'get_player'
                normalization_context:
                    groups: ['player_read', 'player_extra']
            put:
                method: 'PUT'
        collectionOperations:
            post:
                method: 'POST'
                access_control: 'has_role("ROLE_ADMIN")'
            get:
                method: 'GET'
        attributes:
            normalization_context:
                groups: ['player_read']
            denormalization_context:
                groups: ['player_write']
        iri: http://schema.org/Person
        properties:
            'firstName':
                iri: http://schema.org/familyName
            'lastName':
                iri: http://schema.org/givenName

    AppBundle\Entity\Match:
        collectionOperations:
            get:
                method: GET
            post:
                method: POST
            get_mine:
                method: 'GET'
                path: '/me/matches.{_format}'
        itemOperations:
            get:
                method: GET
        attributes:
            normalization_context:
                groups: ['match_read']
            denormalization_context:
                groups: ['match_write']
