api:
    resource: '.'
    type:     'api_platform'
    prefix: /api/v1

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/v1/doc

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

api_login_check:
    path: /api/v1/login-check
    defaults:
        _controller: AppBundle:Authentication:loginCheck
    methods: ['POST']

gesdinet_jwt_refresh_token:
    path:     /api/v1/token/refresh
    defaults:
        _controller: AppBundle:Authentication:refreshToken
    methods: ['POST']

get_player:
    path: /api/v1/players/{id}.{_format}
    defaults:
        _controller: AppBundle:Player:getPlayer
        _api_resource_class: AppBundle\Entity\Player
        _api_item_operation_name: get
        _format: jsonld
    methods: ['GET']
